Update application install logic
civo/cli pull request #184
Opened 2022-02-14 15:12 UTC by haardikdharma10

2022-02-14 15:40 UTC, RealHarshThakur commented
No background/description?

2022-02-14 15:41 UTC, RealHarshThakur commented
I just noticed there's a `-r`  flag on the CLI to mention which apps to not include. So I think we should just use that. 

> civo k3s create -r metrics-server 
would send an empty string in applications field.

2022-02-14 19:53 UTC, haardikdharma10 commented
Thanks @RealHarshThakur, updated the PR.

2022-02-14 19:56 UTC, RealHarshThakur commented
We need to communicate this change to the user too. So it needs some examples/description in the commands

2022-02-14 20:00 UTC, RealHarshThakur requested changes

2022-02-14 20:00 UTC, RealHarshThakur commented on cmd/kubernetes_create.go
> +					if utility.Contains(rmApp, "-metrics-server") || utility.Contains(rmApp, "-traefik-v2-nodeport") {
Are we looping over the same list twice? Can we simply not compare `v` with metrics-server and traefik?

2022-02-14 20:04 UTC, RealHarshThakur commented on cmd/kubernetes_create.go
>  					rmApp = append(rmApp, fmt.Sprintf("-%s", v))
Sending `-` in applications field won't be a thing anymore in the API, so we should probably be removing this too.

2022-02-14 20:07 UTC, RealHarshThakur commented
Couple commands you'll need to ensure are working as part of this PR:

`civo k3s create -a foo` => applications=metrics-server,foo,traefik-v2-nodeport
`civo k3s create -a foo -r metrics-server` => applications=traefik-v2-nodeport,foo

2022-02-14 20:10 UTC, RealHarshThakur commented on cmd/kubernetes_create.go
>  					os.Exit(1)
You'll need to modify the installApplications field pretty much always too to explicitly add metrics server and traefik.

2022-02-15 08:45 UTC, haardikdharma10 commented
> I just noticed there's a `-r` flag on the CLI to mention which apps to not include. So I think we should just use that.
> 
> We need to modify code in such a way that
> 
> > civo k3s create -r metrics-server, traefik-v2-nodeport
> 
> would send an empty string in applications field.

But the user can do something like `civo k3s create -a foo,-traefik-v2-nodeport` instead of using the `-r` flag, right? or no? which will return applications=metrics-server,foo 

I believe we should keep both the options for the user to decide. If the user feels like typing out another flag is inconvenient, he/she can just add `-` in the -a flag.

2022-02-15 09:30 UTC, RealHarshThakur commented
Personally, I don't find using `-`  intuitive to exclude something when passing a list but that could just be me. 
Especially, considering apps can only be removed during creating a cluster.

@andyjeffries  WDYT?

2022-02-15 09:32 UTC, andyjeffries commented
I'm happy having it officially documented as using `-r` but I believe either that or `-` works currently, so we can't break existing customers' usage for such a minor improvement.

2022-02-15 09:36 UTC, RealHarshThakur commented
Skimming the code, I don't think we support it right now. It would be a new thing we'll introduce

2022-02-15 09:37 UTC, andyjeffries commented
If that's the case, I'm happy not adding it. However... I would suggest testing the current CLI against the current API and seeing how it works, rather than a theoretical skim of the code and not finding it.

2022-02-15 10:48 UTC, haardikdharma10 commented
Confirmed that something like `civo k3s create -a foo,-traefik-v2-nodeport` doesn't work. It gives the error - `the app that tries to install -traefik-v2-nodeport is not valid`. So i think we'll go ahead with the `-r` plan and then document it.

2022-02-15 15:47 UTC, RealHarshThakur commented on cmd/kubernetes_test.go
> +		},
Test case for :

 `InstallApplicationsArgs{defaultApps: []string{"metrics-server", "traefik"}, apps: "foo", removeApps: "traefik"}`

2022-02-15 15:51 UTC, RealHarshThakur submitted a review, later dismissed

2022-02-15 15:52 UTC, RealHarshThakur commented
Docs/help info is still missing.

2022-02-16 10:37 UTC, haardikdharma10 commented
Added 👍

2022-02-17 13:18 UTC, RealHarshThakur approved these changes

2022-02-17 13:20 UTC, merged